# Unbind the default prefix
unbind C-b
# Set the new prefix to Ctrl+a
set -g prefix C-f
# Bind Ctrl+f to send the prefix key itself, allowing you to press it twice to send C-a to the underlying shell
bind C-f send-prefix
# set mouse use:w
set -g mouse on
